[build]
default-target = "x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
dockerfile = "cross/Dockerfile"

[target.x86_64-unknown-linux-gnu]
dockerfile = "cross/Dockerfile"

[target.aarch64-unknown-linux-musl]
dockerfile = "cross/Dockerfile"

[target.x86_64-unknown-linux-musl]
dockerfile = "cross/Dockerfile"
